// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4wEm4aJ2bvq29zlUh5pQlR0Fj0xhX9gc',
    appId: '1:340968634355:web:764df3ca1af6025db38486',
    messagingSenderId: '340968634355',
    projectId: 'realprojectmobile',
    authDomain: 'realprojectmobile.firebaseapp.com',
    storageBucket: 'realprojectmobile.appspot.com',
    measurementId: 'G-TZF8BRLK68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1TfViB_MwblLfOErvEfNf37zb0aF_eg',
    appId: '1:340968634355:android:c298a6f58c5f67f2b38486',
    messagingSenderId: '340968634355',
    projectId: 'realprojectmobile',
    storageBucket: 'realprojectmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJhZWt3ebeJhPkL5MnZd2fAZl5Qkow3Zo',
    appId: '1:340968634355:ios:5ee25adfd9dc2a43b38486',
    messagingSenderId: '340968634355',
    projectId: 'realprojectmobile',
    storageBucket: 'realprojectmobile.appspot.com',
    iosClientId: '340968634355-b12oimq3c61cid3k5afairmk5gvv51t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileappProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJhZWt3ebeJhPkL5MnZd2fAZl5Qkow3Zo',
    appId: '1:340968634355:ios:0a51e090e0c8ce91b38486',
    messagingSenderId: '340968634355',
    projectId: 'realprojectmobile',
    storageBucket: 'realprojectmobile.appspot.com',
    iosClientId: '340968634355-ss3qlsu3d1i56a3nlij93cb6vqlq9hbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileappProject.RunnerTests',
  );
}
